pyside6-rcc .\PyRssReader.qrc -o .\PyRssReader_rc.py
pyside6-uic .\PyRssReaderWindow.ui -o .\ui_PyRssReaderWindow.py
pyside6-uic .\PrefsDlg.ui -o .\ui_PrefsDlg.py
pyside6-uic .\NewFeedDlg.ui -o .\ui_NewFeedDlg.py
pyside6-uic .\FeedPropertiesDlg.ui -o .\ui_FeedPropertiesDlg.py
pyside6-uic .\PurgeDlg.ui -o .\ui_PurgeDlg.py
pyside6-uic .\filter_dialog.ui -o .\ui_filter_dialog.py
pyside6-uic .\ad_filter_dialog.ui -o .\ui_ad_filter_dialog.py
pyside6-uic .\filter_manager_dialog.ui -o .\ui_filter_manager_dialog.py
pyside6-uic .\language_filter_dialog.ui -o .\ui_language_filter_dialog.py
